name: build-specs
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HAVE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN != '' }}
      DIFFURI: ${{ secrets.DIFFURI }}
      DIFFPW: ${{ secrets.DIFFPW }}
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      # We’re going to be updating the gh-pages branch, but that
      # happens from two repositories. We must preserve what we
      # don’t change by getting the current version
      - name: Checkout current gh-pages from ${{ github.repository_owner}}/3.0-specification
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner}}/3.0-specification
          ref: gh-pages
          path: build/dist

      - name: Preserve the relevant current gh-pages
        run: |
          mkdir /tmp/save-gh-pages
          if [ -d build/dist/${{ github.ref_name }}/head ]; then
             rsync -ar build/dist/${{ github.ref_name }}/head/ /tmp/save-gh-pages/
          fi

      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Restore the relevant gh-pages
        run: |
          mkdir -p build/dist
          rsync -ar /tmp/save-gh-pages/ build/dist/
          rm -rf /tmp/save-gh-pages

      - name: Setup DeltaXML
        run: |
          echo Setup DeltaXML
          if [[ -z "${DIFFURI}" ]]; then
            echo "DeltaXML unavailable"
          else
            curl -s $DIFFURI | openssl enc -aes-256-cbc -salt -pbkdf2 -d -k $DIFFPW | tar zxf -
          fi

      - name: Build the specifications
        run: |
          ./gradlew

      - name: Cleanup DeltaXML
        run: rm -rf deltaxml

      - name: Deploy to gh-pages on ${{ github.repository_owner}}/3.0-specification
        if: ${{ env.HAVE_ACCESS_TOKEN == 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: ${{ github.repository_owner}}/3.0-specification
          branch: gh-pages
          target-folder: /${{ github.ref_name }}/head
